using System;
using System.Globalization;
using System.IO;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Routing;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Options;
using Lintty.WebInspector.Configuration;
using Lintty.WebInspector.Jobs;
using Lintty.WebInspector.Validation;

namespace Lintty.WebInspector.Endpoints;

/// <summary>
/// Wiring for the four documented routes:
///   POST /api/jobs                     – enqueue
///   GET  /api/jobs/{id}                – poll status
///   GET  /api/jobs/{id}/laudo.pdf      – download PDF
///   GET  /api/jobs/{id}/report.json    – download JSON
/// Plus a simple unauthenticated /healthz for liveness.
/// </summary>
public static class JobsEndpoints
{
    /// <summary>
    /// Registers the four <c>/api/jobs</c> routes. Each route is decorated
    /// with OpenAPI metadata (<c>WithName</c>, <c>WithSummary</c>, status
    /// codes via <c>Produces</c>) so Swashbuckle picks it up.
    /// </summary>
    public static void MapJobs(this IEndpointRouteBuilder routes)
    {
        var group = routes.MapGroup("/api/jobs").WithTags("Jobs");

        group.MapPost("/", CreateJob)
            .WithName("CreateJob")
            .WithSummary("Enqueue a new analysis job")
            .WithDescription(
                "Validates the GitHub URL, runs a metadata pre-flight (existence + size), " +
                "applies per-IP rate limits and queue caps, persists a queued job and returns " +
                "its ULID. The actual clone + engine invocation happens asynchronously in the " +
                "worker; clients poll `GET /api/jobs/{id}`.")
            .Accepts<CreateJobRequest>("application/json")
            .Produces<CreateJobResponse>(StatusCodes.Status202Accepted, "application/json")
            .Produces<ErrorResponse>(StatusCodes.Status400BadRequest, "application/json")
            .Produces<ErrorResponse>(StatusCodes.Status429TooManyRequests, "application/json")
            .Produces<ErrorResponse>(StatusCodes.Status503ServiceUnavailable, "application/json");

        group.MapGet("/{jobId}", GetJob)
            .WithName("GetJob")
            .WithSummary("Poll the status of a job")
            .WithDescription(
                "Returns the current status of a job. The response shape is a single envelope " +
                "with optional fields populated based on the status: `queued` and `running` " +
                "include `stage`; `completed` includes score/grade/violation_count/hard_locks_open " +
                "plus the artifact download URLs and `expires_at`; `failed` includes " +
                "`error_code` and `error_message`. See `JobStatusResponse` for the full shape.")
            .Produces<JobStatusResponse>(StatusCodes.Status200OK, "application/json")
            .Produces<ErrorResponse>(StatusCodes.Status404NotFound, "application/json");

        group.MapGet("/{jobId}/laudo.pdf", GetPdf)
            .WithName("GetJobPdf")
            .WithSummary("Download the audit PDF (laudo) for a completed job")
            .WithDescription(
                "Returns the deterministic PDF (`application/pdf`) generated by the engine. " +
                "Available only when `status == \"completed\"`. The file is byte-identical to " +
                "what the local CLI would produce against the same solution at the same canon " +
                "version. Cached privately for 24h on the client (`Cache-Control: private, max-age=86400`).")
            .Produces(StatusCodes.Status200OK, contentType: "application/pdf")
            .Produces(StatusCodes.Status404NotFound);

        group.MapGet("/{jobId}/report.json", GetJson)
            .WithName("GetJobJson")
            .WithSummary("Download the raw JSON report for a completed job")
            .WithDescription(
                "Returns the compact JSON report bytes — these are the exact bytes whose " +
                "SHA-256 is recorded as `hash_content` in the PDF footer. Available only when " +
                "`status == \"completed\"`.")
            .Produces(StatusCodes.Status200OK, contentType: "application/json")
            .Produces(StatusCodes.Status404NotFound);
    }

    /// <summary>
    /// Registers the unauthenticated liveness probe under the <c>Health</c>
    /// OpenAPI tag.
    /// </summary>
    public static void MapHealth(this IEndpointRouteBuilder routes)
    {
        routes.MapGet("/healthz", () => Results.Ok(new HealthResponse { Status = "ok" }))
            .WithTags("Health")
            .WithName("Healthz")
            .WithSummary("Liveness probe")
            .WithDescription("Returns `200 {\"status\":\"ok\"}` once the host has booted and " +
                "the DI graph is intact. Used by Cloud Run / VM probes.")
            .Produces<HealthResponse>(StatusCodes.Status200OK, "application/json");
    }

    /// <summary>
    /// Implementation of <c>POST /api/jobs</c>. See route registration in
    /// <see cref="MapJobs"/> for the OpenAPI metadata; the doc here is the
    /// authoritative reference for the validation pipeline.
    /// </summary>
    /// <remarks>
    /// Pipeline order:
    /// <list type="number">
    ///   <item><description>Body present? → <c>400 invalid_payload</c>.</description></item>
    ///   <item><description>URL parses + host is github.com? → <c>400 invalid_url</c>.</description></item>
    ///   <item><description>IP under daily quota? → <c>429 rate_limited</c> with <c>Retry-After: 86400</c>.</description></item>
    ///   <item><description>Worker queue under cap? → <c>503 queue_full</c>.</description></item>
    ///   <item><description>Repo exists / not forbidden / under 500 MB? → <c>400 repo_not_accessible|repo_forbidden|repo_too_large</c>.</description></item>
    ///   <item><description>Persist + return <c>202 Accepted</c>.</description></item>
    /// </list>
    /// </remarks>
    private static async Task<IResult> CreateJob(
        HttpContext ctx,
        CreateJobRequest? body,
        IJobStore store,
        IGitHubMetadataClient gh,
        IOptions<RateLimitOptions> rateOpts,
        IOptions<QueueOptions> queueOpts,
        ILoggerFactory logFactory,
        CancellationToken ct)
    {
        var log = logFactory.CreateLogger("JobsEndpoints.CreateJob");

        if (body is null)
            return BadRequest("invalid_payload", "Request body is required and must be JSON.");

        var coords = ValidateUrl(body.GithubUrl, out var urlError);
        if (coords is null) return urlError!;

        var rateLimit = await ValidateRateLimit(ctx, store, rateOpts.Value, ct).ConfigureAwait(false);
        if (rateLimit.RejectResult is not null) return rateLimit.RejectResult;

        var queueGate = await ValidateQueueCapacity(store, queueOpts.Value, ct).ConfigureAwait(false);
        if (queueGate is not null) return queueGate;

        var meta = await ValidateRepoAccess(gh, coords, body.GithubToken, ct).ConfigureAwait(false);
        if (meta.RejectResult is not null) return meta.RejectResult;

        var jobId = await EnqueueJob(store, coords, body, meta.Metadata!, rateLimit.Ip, rateLimit.Day, ct).ConfigureAwait(false);
        log.LogInformation("queued job {JobId} from ip={Ip} owner={Owner} repo={Repo} ref={Ref}",
            jobId, rateLimit.Ip, coords.Owner, coords.Repo, body.Ref ?? meta.Metadata!.DefaultBranch ?? "<default>");

        var resp = new CreateJobResponse
        {
            JobId = jobId,
            Status = JobStatus.Queued,
            PollUrl = $"/api/jobs/{jobId}",
        };
        return Results.Json(resp, statusCode: StatusCodes.Status202Accepted);
    }

    private static GitHubRepoCoordinates? ValidateUrl(string? githubUrl, out IResult? error)
    {
        var coords = UrlValidator.TryParse(githubUrl, out var parseError);
        error = coords is null ? BadRequest("invalid_url", parseError ?? "github_url is invalid.") : null;
        return coords;
    }

    private static async Task<RateLimitDecision> ValidateRateLimit(
        HttpContext ctx,
        IJobStore store,
        RateLimitOptions opts,
        CancellationToken ct)
    {
        // JobsPerIpPerDay <= 0 disables the cap entirely. The counter is still
        // incremented at EnqueueJob so we keep the audit trail even when uncapped.
        var ip = ctx.Connection.RemoteIpAddress?.ToString() ?? "unknown";
        var day = DateTime.UtcNow.ToString("yyyy-MM-dd", CultureInfo.InvariantCulture);
        var dailyCap = opts.JobsPerIpPerDay;
        if (dailyCap > 0)
        {
            var currentCount = await store.GetRateLimitCountAsync(ip, day, ct).ConfigureAwait(false);
            if (currentCount >= dailyCap)
            {
                ctx.Response.Headers["Retry-After"] = "86400";
                var rejection = Results.Json(
                    new ErrorResponse { Error = "rate_limited", Message = $"Limit of {dailyCap} jobs per IP per day exceeded." },
                    statusCode: StatusCodes.Status429TooManyRequests);
                return new RateLimitDecision(ip, day, rejection);
            }
        }
        return new RateLimitDecision(ip, day, null);
    }

    private static async Task<IResult?> ValidateQueueCapacity(IJobStore store, QueueOptions opts, CancellationToken ct)
    {
        var active = await store.CountActiveAsync(ct).ConfigureAwait(false);
        if (active >= opts.MaxLength)
        {
            return Results.Json(
                new ErrorResponse { Error = "queue_full", Message = "Worker is busy. Try again in a few minutes or use the local CLI." },
                statusCode: StatusCodes.Status503ServiceUnavailable);
        }
        return null;
    }

    private static async Task<RepoAccessDecision> ValidateRepoAccess(
        IGitHubMetadataClient gh,
        GitHubRepoCoordinates coords,
        string? token,
        CancellationToken ct)
    {
        // We don't fail just because the metadata API is slow/down; we DO fail
        // on definitive 404 or oversize repo, per spec §6.
        var meta = await gh.GetMetadataAsync(coords, token, ct).ConfigureAwait(false);
        if (!meta.Exists)
            return new RepoAccessDecision(null, BadRequest("repo_not_accessible", "Repository not found or not accessible. Provide a github_token or use the local CLI."));
        if (meta.Forbidden)
            return new RepoAccessDecision(null, BadRequest("repo_forbidden", "Repository requires authentication. Provide a github_token with `repo` scope."));

        const long maxKb = 500L * 1024L; // 500 MB
        if (meta.SizeKilobytes > maxKb)
            return new RepoAccessDecision(null, BadRequest("repo_too_large", "Repos over 500 MB must use the local CLI. Download it from lintty.com."));

        return new RepoAccessDecision(meta, null);
    }

    private static async Task<string> EnqueueJob(
        IJobStore store,
        GitHubRepoCoordinates coords,
        CreateJobRequest body,
        Lintty.WebInspector.Validation.GitHubRepoMetadata meta,
        string ip,
        string day,
        CancellationToken ct)
    {
        var jobId = Ulid.New();
        var job = new Job
        {
            Id = jobId,
            GithubUrl = coords.NormalizedUrl.ToString(),
            Ref = string.IsNullOrEmpty(body.Ref) ? meta.DefaultBranch : body.Ref,
            SolutionPath = body.SolutionPath,
            Status = JobStatus.Queued,
            CreatedAt = DateTime.UtcNow,
        };
        await store.InsertJobAsync(job, ct).ConfigureAwait(false);
        await store.IncrementRateLimitAsync(ip, day, ct).ConfigureAwait(false);

        // Token (PAT) is intentionally not persisted. The clone path is
        // public-only in V0; the response is unchanged so the API contract
        // for v1 stays compatible.
        return jobId;
    }

    private sealed record RateLimitDecision(string Ip, string Day, IResult? RejectResult);

    private sealed record RepoAccessDecision(
        Lintty.WebInspector.Validation.GitHubRepoMetadata? Metadata,
        IResult? RejectResult);

    /// <summary>
    /// Implementation of <c>GET /api/jobs/{id}</c>. Returns
    /// <c>404 not_found</c> for either a malformed ULID or an unknown id.
    /// </summary>
    private static async Task<IResult> GetJob(
        string jobId,
        IJobStore store,
        CancellationToken ct)
    {
        if (!Ulid.IsValid(jobId))
            return Results.NotFound(new ErrorResponse { Error = "not_found", Message = "Unknown job_id." });
        var job = await store.GetAsync(jobId, ct).ConfigureAwait(false);
        if (job is null)
            return Results.NotFound(new ErrorResponse { Error = "not_found", Message = "Unknown job_id." });

        var resp = new JobStatusResponse
        {
            JobId = job.Id,
            Status = job.Status,
            Stage = job.Stage,
        };

        if (job.Status == JobStatus.Completed)
        {
            resp.Score = job.Score;
            resp.Grade = job.Grade;
            resp.CanonVersion = job.CanonVersion;
            resp.ViolationCount = job.ViolationCount;
            resp.HardLocksOpen = job.HardLocksOpen;
            resp.PdfUrl = $"/api/jobs/{job.Id}/laudo.pdf";
            resp.JsonUrl = $"/api/jobs/{job.Id}/report.json";
            resp.ExpiresAt = job.ExpiresAt?.ToString("o", CultureInfo.InvariantCulture);
        }
        else if (job.Status == JobStatus.Failed)
        {
            resp.ErrorCode = job.ErrorCode;
            resp.ErrorMessage = job.ErrorMessage;
        }

        return Results.Json(resp, statusCode: StatusCodes.Status200OK);
    }

    /// <summary>
    /// Implementation of <c>GET /api/jobs/{id}/laudo.pdf</c>. Streams the PDF
    /// bytes; 404 if the job isn't completed, the artifact path is missing,
    /// or the file no longer exists on disk (TTL cleanup).
    /// </summary>
    private static async Task<IResult> GetPdf(string jobId, IJobStore store, CancellationToken ct)
    {
        var job = await ResolveCompletedAsync(jobId, store, ct).ConfigureAwait(false);
        if (job is null || job.PdfPath is null || !File.Exists(job.PdfPath))
            return Results.NotFound();
        var bytes = await File.ReadAllBytesAsync(job.PdfPath, ct).ConfigureAwait(false);
        return Results.File(bytes, "application/pdf", fileDownloadName: "laudo.pdf");
    }

    /// <summary>
    /// Implementation of <c>GET /api/jobs/{id}/report.json</c>. Streams the
    /// compact JSON bytes used to compute <c>hash_content</c>.
    /// </summary>
    private static async Task<IResult> GetJson(string jobId, IJobStore store, CancellationToken ct)
    {
        var job = await ResolveCompletedAsync(jobId, store, ct).ConfigureAwait(false);
        if (job is null || job.JsonPath is null || !File.Exists(job.JsonPath))
            return Results.NotFound();
        var bytes = await File.ReadAllBytesAsync(job.JsonPath, ct).ConfigureAwait(false);
        return Results.File(bytes, "application/json", fileDownloadName: "report.json");
    }

    private static async Task<Job?> ResolveCompletedAsync(string jobId, IJobStore store, CancellationToken ct)
    {
        if (!Ulid.IsValid(jobId)) return null;
        var job = await store.GetAsync(jobId, ct).ConfigureAwait(false);
        if (job is null || job.Status != JobStatus.Completed) return null;
        return job;
    }

    private static IResult BadRequest(string code, string message)
        => Results.Json(new ErrorResponse { Error = code, Message = message }, statusCode: StatusCodes.Status400BadRequest);
}

/// <summary>
/// Response shape for <c>GET /healthz</c>.
/// </summary>
public sealed class HealthResponse
{
    /// <summary>Always <c>"ok"</c> when the host is alive.</summary>
    /// <example>ok</example>
    [System.Text.Json.Serialization.JsonPropertyName("status")]
    public string Status { get; set; } = string.Empty;
}
