using System;

namespace Lintty.WebInspector.Persistence.Entities;

/// <summary>
/// An org-bound scan request, the multi-tenant counterpart to the V0 anonymous
/// <see cref="Lintty.WebInspector.Jobs.Job"/>. Sprint 3 of ADR 0007 §3.7 —
/// PR 1 lands the schema only; the <c>ScanService</c>, the
/// <c>POST /api/scans</c> endpoint, and the worker integration follow in
/// PR 4.
///
/// **Coexists with <see cref="Lintty.WebInspector.Jobs.Job"/>.** Per ADR 0007
/// §3.4 + Apêndice E redesign, the V0 anonymous flow keeps writing into
/// <c>jobs</c> (Dapper, untouched). <c>scans</c> is a separate table — the
/// worker will learn to drain both queues in PR 4. Do NOT migrate <c>jobs</c>
/// rows here.
///
/// **Determinism invariants (the cross gate):**
/// <list type="bullet">
/// <item><see cref="CanonVersion"/> is snapshotted at trigger time, not at
/// worker pickup. A scan queued today against canon <c>1.0.0</c> must run with
/// <c>1.0.0</c> even if the canon advances before the worker claims it.</item>
/// <item><see cref="HashContent"/> is filled when <see cref="Status"/> reaches
/// <c>completed</c>. It must equal the <c>hash_content</c> the CLI would
/// produce against <c>(github_url, ref, canon_version)</c>. This is the
/// invariant <c>WorkerIntegrationTests.DashboardScan_*</c> will verify in
/// PR 4.</item>
/// </list>
///
/// **<see cref="PublicId"/>** is the URL-facing identifier
/// (<c>/api/scans/{public_id}</c>). UUID v4, generated server-side by Postgres
/// (<c>gen_random_uuid()</c>) so even races during insert can't collide. The
/// numeric <see cref="Id"/> stays internal — never goes in URLs (enumeration
/// vector).
/// </summary>
public sealed class Scan
{
    public long Id { get; set; }

    /// <summary>Public, non-enumerable handle. Used in routes
    /// <c>/api/scans/{public_id}</c> and in PDF/JSON artifact filenames.
    /// Generated by <c>gen_random_uuid()</c> server-side; client never sets
    /// this.</summary>
    public Guid PublicId { get; set; }

    public long OrgId { get; set; }
    public Org? Org { get; set; }

    public long RepoId { get; set; }
    public Repo? Repo { get; set; }

    /// <summary>User who triggered the scan. <b>ON DELETE RESTRICT</b>: a user
    /// who triggered any scan can't be hard-deleted while history exists.
    /// Symmetry with <see cref="Repo.AddedByUserId"/>.</summary>
    public long TriggeredByUserId { get; set; }
    public User? TriggeredByUser { get; set; }

    /// <summary>Branch / tag / sha override. <c>null</c> means "use the
    /// repo's default branch" — the worker resolves it via
    /// <see cref="Repo.DefaultBranch"/> or falls back to the git default.</summary>
    public string? Ref { get; set; }

    /// <summary>Canon version snapshot taken at trigger time. Passed to
    /// <c>lintty-engine analyze --canon-version</c>. <b>Determinism
    /// invariant</b> — see class doc.</summary>
    public string CanonVersion { get; set; } = string.Empty;

    /// <summary>Lifecycle stage. Persisted as a free-form string with a
    /// CHECK constraint enforcing <see cref="ScanStatus"/> values; the
    /// constant pattern mirrors <c>OrgRole</c>.</summary>
    public string Status { get; set; } = ScanStatus.Queued;

    public DateTime QueuedAt { get; set; } = DateTime.UtcNow;
    public DateTime? StartedAt { get; set; }
    public DateTime? CompletedAt { get; set; }

    /// <summary>Free-form error message when <see cref="Status"/> is
    /// <c>failed</c>. Structured <c>error_code</c> (e.g.
    /// <c>GITHUB_TOKEN_REVOKED</c>) is added in PR 4 alongside the worker
    /// changes — Apêndice E §E.9.</summary>
    public string? Error { get; set; }

    /// <summary>SHA-256 of the engine JSON output (<c>"sha256:..."</c>).
    /// Filled when <see cref="Status"/> reaches <c>completed</c>. Cross-gate
    /// of determinism: must equal the CLI's <c>hash_content</c> for the same
    /// (github_url, ref, canon_version).</summary>
    public string? HashContent { get; set; }

    /// <summary>
    /// Per-scan target path, relative to the cloned repo root (forward
    /// slashes). Sprint 3 PR S2 — replaces the runtime-yaml synthesis path.
    /// <list type="bullet">
    ///   <item><description><c>null</c> → auto-detect (V0 anonymous-style).
    ///         The resolver picks the .sln, lintty.yml, or lone .csproj.</description></item>
    ///   <item><description>A <c>.sln</c> or <c>.csproj</c> path → the worker
    ///         resolves it inside the clone and passes <c>--target</c> to
    ///         the engine subprocess.</description></item>
    /// </list>
    /// <para>
    /// One target per scan row. Triggering with N targets creates N rows;
    /// each row carries one <see cref="Target"/> and produces its own PDF.
    /// <c>lintty.yml</c> entries are NOT accepted here — the
    /// <c>POST /api/scans</c> endpoint rejects them at trigger time because
    /// a yaml without a <c>projects:</c> declaration would fail the
    /// resolver. yaml-as-target is preserved for the V0 anonymous flow
    /// (jobs table) where the engine's own auto-detect handles it.
    /// </para>
    /// </summary>
    public string? Target { get; set; }
}

/// <summary>
/// Allowed values for <see cref="Scan.Status"/>. String constants instead of
/// a CLR enum so values stored in Postgres stay stable, readable in SQL, and
/// the CHECK constraint matches them verbatim. Mirrors the
/// <see cref="OrgRole"/> pattern.
/// </summary>
public static class ScanStatus
{
    public const string Queued = "queued";
    public const string Running = "running";
    public const string Completed = "completed";
    public const string Failed = "failed";
    public const string Cancelled = "cancelled";

    public static bool IsValid(string? status)
        => status is Queued or Running or Completed or Failed or Cancelled;
}
