using System;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Text;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Options;
using Lintty.WebInspector.Configuration;

namespace Lintty.WebInspector.Jobs;

/// <summary>
/// Invokes the Lintty engine CLI as a subprocess via <c>dotnet exec</c>.
/// Subprocess (vs library reference) is mandatory by spec §10: the
/// cross-determinism gate of <c>13-web-inspector.md</c> requires that the
/// PDF generated through the Web Inspector is BYTE-IDENTICAL to a PDF
/// generated by the local CLI on the same .sln. Sharing the binary is the
/// only way to keep that promise as the engine evolves.
///
/// We force <c>CultureInfo.InvariantCulture</c> via env vars (LANG=C, LC_ALL=C
/// on Linux; DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=1 always) so the child
/// process matches our InvariantGlobalization guarantee even if a sysadmin
/// has set a non-C locale.
/// </summary>
public sealed class EngineSubprocessRunner : IEngineRunner
{
    private readonly EngineOptions _options;
    private readonly ILogger<EngineSubprocessRunner> _logger;

    public EngineSubprocessRunner(IOptions<EngineOptions> options, ILogger<EngineSubprocessRunner> logger)
    {
        _options = options.Value;
        _logger = logger;
    }

    public async Task<EngineRunResult> RunAsync(
        string targetPath,
        string jsonOutputPath,
        string pdfOutputPath,
        CancellationToken ct)
    {
        var dll = ResolveCliDll();
        if (dll is null)
        {
            return new EngineRunResult(2,
                "lintty-engine.dll not found. Set Engine:CliDllPath in appsettings.json or build the Lintty.Engine.Cli project.");
        }

        var psi = BuildProcessStartInfo(dll, targetPath, jsonOutputPath, pdfOutputPath);
        _logger.LogInformation("engine: dotnet {Args}", psi.Arguments);

        using var process = new Process { StartInfo = psi, EnableRaisingEvents = true };
        var stderrBuf = new StringBuilder();
        process.ErrorDataReceived += (_, e) => { if (e.Data is not null) stderrBuf.AppendLine(e.Data); };

        if (!TryStart(process, out var startError))
            return startError!;

        CaptureStreams(process, ct);

        var timeoutResult = await EnforceTimeout(process, ct).ConfigureAwait(false);
        if (timeoutResult is not null) return timeoutResult;

        return new EngineRunResult(process.ExitCode, stderrBuf.ToString());
    }

    private ProcessStartInfo BuildProcessStartInfo(
        string dll,
        string targetPath,
        string jsonOutputPath,
        string pdfOutputPath)
    {
        // Compose argv. We pass --output-file so the JSON does not pollute
        // stdout (we capture stderr for log purposes anyway). --fail-on-grade=F
        // ensures exit code 0 for any grade — we want to differentiate
        // "ran cleanly" from "execution error" downstream.
        //
        // ADR 0006: --target accepts .sln, .csproj, or lintty.yml. The worker
        // resolves the path in-process (TargetResolver) and feeds the concrete
        // file path here.
        var args = new StringBuilder();
        args.Append("exec ").Append(QuoteArg(dll));
        args.Append(" analyze");
        args.Append(" --target ").Append(QuoteArg(targetPath));
        args.Append(" --pdf ").Append(QuoteArg(pdfOutputPath));
        args.Append(" --output-file ").Append(QuoteArg(jsonOutputPath));
        args.Append(" --fail-on-grade F");

        var psi = new ProcessStartInfo
        {
            FileName = "dotnet",
            Arguments = args.ToString(),
            RedirectStandardOutput = true,
            RedirectStandardError = true,
            UseShellExecute = false,
            CreateNoWindow = true,
            WorkingDirectory = Path.GetDirectoryName(targetPath) ?? Directory.GetCurrentDirectory(),
        };
        psi.Environment["LANG"] = "C";
        psi.Environment["LC_ALL"] = "C";
        psi.Environment["DOTNET_SYSTEM_GLOBALIZATION_INVARIANT"] = "1";
        // Disable .NET telemetry / first-run experience so they don't add stderr noise.
        psi.Environment["DOTNET_CLI_TELEMETRY_OPTOUT"] = "1";
        psi.Environment["DOTNET_NOLOGO"] = "1";
        psi.Environment["DOTNET_SKIP_FIRST_TIME_EXPERIENCE"] = "1";

        return psi;
    }

    private static bool TryStart(Process process, out EngineRunResult? error)
    {
        try
        {
            if (!process.Start())
            {
                error = new EngineRunResult(2, "dotnet failed to start.");
                return false;
            }
        }
        catch (Exception ex)
        {
            error = new EngineRunResult(2, $"dotnet start failed: {ex.Message}");
            return false;
        }
        error = null;
        return true;
    }

    private static void CaptureStreams(Process process, CancellationToken ct)
    {
        process.BeginErrorReadLine();
        // We don't care about stdout content but draining it avoids deadlock.
        _ = process.StandardOutput.ReadToEndAsync(ct);
    }

    private async Task<EngineRunResult?> EnforceTimeout(Process process, CancellationToken ct)
    {
        var runCt = CancellationTokenSource.CreateLinkedTokenSource(ct);
        runCt.CancelAfter(TimeSpan.FromSeconds(_options.JobTimeoutSeconds));
        try
        {
            await process.WaitForExitAsync(runCt.Token).ConfigureAwait(false);
            return null;
        }
        catch (OperationCanceledException)
        {
            TryKill(process);
            // We surface timeout as a special exit-code-127 sentinel; the
            // caller maps it to JobErrorCode.Timeout.
            return new EngineRunResult(127,
                ct.IsCancellationRequested
                    ? "engine cancelled"
                    : $"engine exceeded {_options.JobTimeoutSeconds}s timeout");
        }
    }

    /// <summary>
    /// Finds the engine CLI dll. Order:
    /// 1. <c>Engine:CliDllPath</c> if explicitly configured (production deployments).
    /// 2. Sibling project layout, preferring the same build config as the host
    ///    (Release if running under <c>bin/Release/...</c>, Debug otherwise).
    ///    Falls back to the most recently written dll if the preferred config
    ///    is absent — guards against stale Debug dlls when the WebInspector
    ///    runs Release but a Debug build sits next to it.
    /// 3. Direct bin layout (when a publish step copied the dll alongside).
    /// </summary>
    private string? ResolveCliDll()
    {
        if (!string.IsNullOrEmpty(_options.CliDllPath))
        {
            return File.Exists(_options.CliDllPath) ? _options.CliDllPath : null;
        }

        var hostAssembly = Assembly.GetEntryAssembly() ?? typeof(EngineSubprocessRunner).Assembly;
        var hostDir = Path.GetDirectoryName(hostAssembly.Location);
        if (string.IsNullOrEmpty(hostDir)) return null;

        var preferredConfig = InferBuildConfig(hostDir);

        var dir = new DirectoryInfo(hostDir);
        for (var i = 0; i < 8 && dir is not null; i++, dir = dir.Parent)
        {
            var sibling = Path.Combine(dir.FullName, "..", "..", "..", "Lintty.Engine.Cli", "bin");
            if (Directory.Exists(sibling))
            {
                var found = SelectBestCliDll(sibling, preferredConfig);
                if (found is not null) return found;
            }

            var local = Path.Combine(dir.FullName, "lintty-engine.dll");
            if (File.Exists(local)) return local;
        }
        return null;
    }

    /// <summary>
    /// Looks at the host's bin path (<c>.../bin/Release/net8.0/</c>) and
    /// returns "Release" or "Debug". Defaults to "Release" when the path
    /// does not contain either marker (e.g., a published deployment).
    /// </summary>
    private static string InferBuildConfig(string hostDir)
    {
        var normalized = hostDir.Replace('\\', '/');
        if (normalized.Contains("/bin/Debug/", StringComparison.OrdinalIgnoreCase)) return "Debug";
        if (normalized.Contains("/bin/Release/", StringComparison.OrdinalIgnoreCase)) return "Release";
        return "Release";
    }

    private static string? SelectBestCliDll(string binRoot, string preferredConfig)
    {
        try
        {
            // 1) Exact preferred config: bin/<preferred>/<tfm>/lintty-engine.dll
            var preferredDir = Path.Combine(binRoot, preferredConfig);
            if (Directory.Exists(preferredDir))
            {
                var match = Directory.EnumerateFiles(preferredDir, "lintty-engine.dll", SearchOption.AllDirectories)
                    .OrderByDescending(File.GetLastWriteTimeUtc)
                    .FirstOrDefault();
                if (match is not null) return match;
            }

            // 2) Anything under bin/, freshest first. Prevents accidental selection
            //    of a stale Debug dll alphabetically ahead of a fresher Release dll.
            return Directory.EnumerateFiles(binRoot, "lintty-engine.dll", SearchOption.AllDirectories)
                .OrderByDescending(File.GetLastWriteTimeUtc)
                .FirstOrDefault();
        }
        catch
        {
            return null;
        }
    }

    private static void TryKill(Process p)
    {
        try { if (!p.HasExited) p.Kill(entireProcessTree: true); }
        catch { /* best effort */ }
    }

    private static string QuoteArg(string s) => $"\"{s}\"";
}
