<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>Lintty.Engine.Cli</RootNamespace>
    <AssemblyName>lintty-engine</AssemblyName>
    <InvariantGlobalization>true</InvariantGlobalization>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.CommandLine" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Lintty.Engine.Core\Lintty.Engine.Core.csproj" />
    <ProjectReference Include="..\Lintty.Engine.Reporter\Lintty.Engine.Reporter.csproj" />
  </ItemGroup>

</Project>
