<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Lintty.Engine.Cli\Lintty.Engine.Cli.csproj" />
    <ProjectReference Include="..\..\src\Lintty.Engine.Core\Lintty.Engine.Core.csproj" />
  </ItemGroup>

</Project>
