<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Lintty.Engine.Core</RootNamespace>
    <AssemblyName>Lintty.Engine.Core</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp.Workspaces" />
    <PackageReference Include="Microsoft.CodeAnalysis.Workspaces.MSBuild" />
    <PackageReference Include="Microsoft.Build.Locator" />
    <PackageReference Include="YamlDotNet" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Lintty.Engine.Core.Tests" />
    <InternalsVisibleTo Include="Lintty.Engine.Cli" />
  </ItemGroup>

</Project>
